#!/bin/sh

# a special version of dmenu_run that remembers the most-recently used items
# and shows them first when the menu first pops up

RECENT_FILE="${1:-$HOME/.dmenu.recent}"

{
  [[ -s "$RECENT_FILE" ]] && cat "$RECENT_FILE"
  dmenu_path
} \
  | dmenu "$@" \
  | dmenu_recent \
  | ${SHELL:-"/bin/sh"} &

