#! /usr/bin/env bash

set -euo pipefail

# take stdin, append it to the recent file and output it
# this should be used in a dmenu chain to remember recent choices

recent_file="${1:-$HOME/.dmenu.recent}"
recent_count=${DMENU_RECENT_ITEMS:-6}

# read in the file
# remove any occurances of the passed item
# prepend the item to the list
# output only the last 'n' items

selection="$( cat )"

if [[ -s "$recent_file" ]]; then
  recent_items="$( grep -v "^$selection\$" "$recent_file" || true )"
  mapfile -t recent_items <<< "$recent_items"

  # prepend the selection to the list
  recent_items=("$selection" "${recent_items[@]}")
else
  recent_items=("$selection")
fi

# clobber the recent file with our recent items
printf "%s\n" "${recent_items[@]}" \
  | head -n "$recent_count" \
  > "$recent_file"

echo "$selection"

